version: "3.8"

networks:
  service-net:
    name: mynet2


services:
  postgres-db:
    image: bitnami/postgresql:latest
    hostname: nzedi-api-postgres
    container_name: nzedi-api-postgres
    ports:
      - 5432:5433
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=nzedi_eshop
    networks:
      - service-net

#  dit-kay-eshop-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: dit-kay-eshop-api-image
#    ports:
#      - 3001:3001
#    environment:
#      - HTTP_SERVER_PORT=3001
#      - AWS_REGION="eu-west-2"
#      - APP_LOG_LEVEL=INFO
#      - DB_PORT=5432
#      - DB_HOST=ditkay-eshop-api-postgres
#      - DB_USERNAME=root
#      - DB_PASSWORD=root
#      - DB_NAME=ditkay_eshop
#    networks:
#      - service-net
#    links:
#      - postgres-db
