version: "3.8"

networks:
  service-net:
    name: mynet


services:
  nzedi-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: 0816048957docker/nzedi-api:latest
    ports:
      - 3002:3002
    environment:
      - HTTP_SERVER_PORT=3002
      - AWS_REGION="eu-west-2"
      - APP_LOG_LEVEL=INFO
      - DB_PORT=5432
      - DB_HOST=ditkay-eshop-api-postgres
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=nzedi_eshop
    networks:
      - service-net
#    links:
#      - postgres-db
